[package]
name = "disturbulence"
version = "0.1.0"
edition = "2024"

[dependencies]
fftw = { git = "https://github.com/kmaitreys/fftw3-rs.git", branch = "master" }
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.0"
ndarray = "0.16.1"
num-complex = "0.4.6"
